import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cyber Portfolio",
  description: "Modern Cyberpunk Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased bg-black text-green-500 font-mono"
    >
      <body className="min-h-full flex flex-col border-2 border-green-900 m-2 p-4">{children}</body>
    </html>
  );
}
